language: erlang
otp_release:
  - 18.1
  - 18.0
  - 17.0
  - 17.1
  - R16B03
  - R16B02
  - R16B01
  - R16B
before_install:
  - sudo pip install -q httpbin
  - sudo pip install -q gunicorn
before_script: gunicorn httpbin:app&
